
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOL_OP_BI BOOL_OP_UN Comp_OP EQUALS F FLOAT INT NUM_OP_BI NUM_OP_UN Tint : INTfloat : FLOATexpression : int\n| floatint : INT NUM_OP_UNfloat : float NUM_OP_UNint : int int NUM_OP_BIfloat : float float NUM_OP_BI\n| int float NUM_OP_BI\n| float int NUM_OP_BI'
    
_lr_action_items = {'INT':([0,1,2,3,4,5,],[2,2,-1,2,-5,-7,]),'$end':([1,2,4,5,],[0,-1,-5,-7,]),'NUM_OP_BI':([2,3,4,5,],[-1,5,-5,-7,]),'NUM_OP_UN':([2,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'int':([0,1,3,],[1,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> int","S'",1,None,None,None),
  ('int -> INT','int',1,'p_expression_int','vanilla_parser.py',27),
  ('float -> FLOAT','float',1,'p_expression_float','vanilla_parser.py',29),
  ('expression -> int','expression',1,'p_expression_e','vanilla_parser.py',31),
  ('expression -> float','expression',1,'p_expression_e','vanilla_parser.py',32),
  ('int -> INT NUM_OP_UN','int',2,'p_expression_int_op_un','vanilla_parser.py',35),
  ('float -> float NUM_OP_UN','float',2,'p_expression_float_op_un','vanilla_parser.py',39),
  ('int -> int int NUM_OP_BI','int',3,'p_expression_int_op_bi','vanilla_parser.py',44),
  ('float -> float float NUM_OP_BI','float',3,'p_expression_float_op_bi','vanilla_parser.py',48),
  ('float -> int float NUM_OP_BI','float',3,'p_expression_float_op_bi','vanilla_parser.py',49),
  ('float -> float int NUM_OP_BI','float',3,'p_expression_float_op_bi','vanilla_parser.py',50),
]
